### PR TITLE
This allows to Build stand alone Kernels as well:

### PR DESCRIPTION
**Pull request by Eliminater74**
These 2 commits taken from Nathans CLANG repo, allows to build standalone kernels with latest CLANG and GCC, Tested on Release 8 and now testing on Release 9....

### CODE REVIEW

**Comment by mydongistiny** [comment]
What do you mean?

Edit: The Clang suffix patch isn't needed. We already pass the revision in the build script, but as the date of the build using CLANG_TC_DATE. https://github.com/dragon-tc-tmp/clang/commit/910ed72ec7c651ece01b21e998b1739b99091002

I can add the local-init sanitizer commit, but I don't know what you mean by build stand alone kernels for Clang and GCC. They already build and work with Clang, but I don't understand how GCC comes into it.

**Comment by Eliminater74** [comment]
> What do you mean?
> 
> Edit: The Clang suffix patch isn't needed. We already pass the revision in the build script, but as the date of the build using CLANG_TC_DATE. [910ed72](https://github.com/dragon-tc-tmp/clang/commit/910ed72ec7c651ece01b21e998b1739b99091002)
> 
> I can add the local-init sanitizer commit, but I don't know what you mean by build stand alone kernels for Clang and GCC. They already build and work with Clang, but I don't understand how GCC comes into it.

What I mean is, I build a stand alone kernel, Not with Android Tree, and to use a custom CLANG, that local-init sanitizer is needed or else the build with fail with errors..

The GCC is only needed for the linking as you already know this..
Sorry I might have said that wrong before... Anyhow, I use your work.. I build the clang, and build my kernel 4.9.x for my Oneplus 6T, No problems at all.. but yeah I had to add that commit for it all to work right. I verified all this with Nathan beforehand..

**Comment by mydongistiny** [comment]
> What I mean is, I build a stand alone kernel, Not with Android Tree, and to use a custom CLANG, that local-init sanitizer is needed or else the build with fail with errors..

Can I see what build error you get? I can build mine separate from the Android tree using a simple bash script I made. Just curious what it is.

**Comment by Eliminater74** [comment]
> > What I mean is, I build a stand alone kernel, Not with Android Tree, and to use a custom CLANG, that local-init sanitizer is needed or else the build with fail with errors..
> 
> Can I see what build error you get? I can build mine separate from the Android tree using a simple bash script I made. Just curious what it is.

Running a build with none of my extra stuff added, and going to try a kernel build after that.. ill paste the errors if I get any.. If not, then ill let you know that too..

Just give me a bit before I can try it.

**Comment by mydongistiny** [comment]
No rush. I merged the init-local commit locally and am going to push it, but I just want to see what the error says. Like I said I build mine out of the Android tree with just a build script: 

https://pastebin.com/bXUmkNYW

**Comment by Eliminater74** [comment]
> No rush. I merged the init-local commit locally and am going to push it, but I just want to see what the error says. Like I said I build mine out of the Android tree with just a build script:
> 
> [pastebin.com/bXUmkNYW](https://pastebin.com/bXUmkNYW)

well you were right, I built DTC with everything left as you have it, and built my kernel standalone and everything worked...... But I do have one question for you since you use POLLY on your kernel, and I kinda do, but
When I add -mllvm -polly-parallel -lgomp to flags,

I end up with this error under qcacld-3.0:

`  AR      built-in.o
  LD      vmlinux.o
  LD      vmlinux.o
  MODPOST vmlinux.o
  LD      vmlinux
drivers/staging/qcacld-3.0/core/wma/src/wma_scan_roam.o: In function `wma_start_extscan':
wma_scan_roam.c:(.text+0x4b4c): undefined reference to `GOMP_parallel_loop_runtime_start'
wma_scan_roam.c:(.text+0x4b4c): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `GOMP_parallel_loop_runtime_start'
wma_scan_roam.c:(.text+0x4b58): undefined reference to `GOMP_parallel_end'
wma_scan_roam.c:(.text+0x4b58): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `GOMP_parallel_end'
drivers/staging/qcacld-3.0/core/wma/src/wma_scan_roam.o: In function `wma_start_extscan_polly_subfn':
wma_scan_roam.c:(.text+0x5c08): undefined reference to `GOMP_loop_runtime_next'
wma_scan_roam.c:(.text+0x5c08): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `GOMP_loop_runtime_next'
wma_scan_roam.c:(.text+0x5d20): undefined reference to `GOMP_loop_runtime_next'
wma_scan_roam.c:(.text+0x5d20): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `GOMP_loop_runtime_next'
wma_scan_roam.c:(.text+0x5d34): undefined reference to `GOMP_loop_end_nowait'
wma_scan_roam.c:(.text+0x5d34): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `GOMP_loop_end_nowait'
make[1]: *** [/home/eliminater74/Builds/kernel/OP/android-linux-stable-op6t_20190123/Makefile:1157: vmlinux] Error 1
make[1]: Leaving directory '/home/eliminater74/Builds/kernel/OP/android-linux-stable-op6t_20190123/out'
make: *** [Makefile:152: sub-make] Error 2`

Here is my Makefile: https://gitlab.com/devoneplus/android-linux-stable-op6t/blob/nebula_WIP_20190204/Makefile

I can get POLLY working with all other options just not that one..
but thats the best option of all, I did try and disable the use of POLLY under the qcacld, but that failed as well.. so im lost is it possible you can take a look and tell me what I might be doing wrong there..

and thanks for your help...

Current clang worked like a charm.. except for the POLLY issue that I have always had.....

also I did test this on a few dif GCC's including AOSP's default master branch prebuilts, and still no go.. even tested on custom as well.........

GCC meaning, for the linker.......

**Comment by mydongistiny** [comment]
Not sure why you're getting that gomp error. Polly should be adding the linker flags when building. You can either remove the -lgomp line or try adding it or -lgmp to the linking flags. You could probably also use -fopenmp in the cflags and see if that makes it go away without adding new link flags.

**Comment by Eliminater74** [comment]
> Not sure why you're getting that gomp error. Polly should be adding the linker flags when building. You can either remove the -lgomp line or try adding it or -lgmp to the linking flags. You could probably also use -fopenmp in the cflags and see if that makes it go away without adding new link flags.

yeah I tried all that too. I dont get it.. and it seems to be only with qcacld, funny cause with the 4.9 kernel it doesnt come with techpack/audio or qcacld-3.0, both you have to merge externally, I wonder if thats the problem.. but again, Techpack/audio seems to work with no issues. its only qcacld. I even tried to add the cflags ldflags dir to the drivers/staging/makefile under the config option for qcacld.. that gave me same results as adding it to main Makefile.........

I been messing with this problem for a while now, I just thought you might have an idea on whats going on.. Guess your just as stumped as I am. Which sucks, because that flag is the #1 main flag that makes POLLY what it is........ Owell,
Thanks for your help anyhow.......

**Comment by mydongistiny** [comment]
-Removed original reply-

I downloaded the source to test it. I'll see if I can figure it out.

**Comment by Eliminater74** [comment]
> -Removed original reply-
> 
> I downloaded the source to test it. I'll see if I can figure it out.

[build.log](https://github.com/dragon-tc-tmp/clang/files/2848095/build.log)

Here is build_log with only qcacld-3.0, as for as I can tell, nothing in ldlinker other then this: + local 'ld=/home/eliminater74/Builds/kernel/toolchains/GoogleTC/gcc-arm-8.2-2019.01-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-ld.bfd -EL'
+ local 'ldflags= --no-undefined -X --build-id  -X'

so im a bit lost on that..

**Comment by mydongistiny** [comment]
For now if you want to use polly for the kernel I made a patch that allows the build to finish. It just disables polly for qcacld-3.0:

https://gist.github.com/mydongistiny/585e86c4b3cf266ae0e72bae60d328d6

**Comment by Eliminater74** [comment]
> For now if you want to use polly for the kernel I made a patch that allows the build to finish. It just disables polly for qcacld-3.0:
> 

It worked, and it booted, Thanks for all your help man, to even take the time to help me with that.. thank you so much..... I ran the GIT am filename.patch, so that your original authorship and commit is kept.. chances are many people will pick from me on.. I do tell people that unless they are using DTC by you, chances are it wont build if anyone uses my Makefile adjustments...  But once again, thank you..

**Comment by mydongistiny** [comment]
No problem. Glad it's working for now. I'll still try and figure out the underlying problem when I get a chance. I have an idea, but not sure how to fix it right now without looking deeper into it.

**Pull request closed without merging**
